feat: restyling login and register pages
openhotel/auth pull request #168
Opened 2024-11-30 18:08 UTC by cout970

Adds new styles for login and register.
Added error messages when register fails.
Handle edge case when the backend response is empty of non-json.

Has a bug with max-height of container https://github.com/openhotel/components/issues/4

2024-11-30 18:10 UTC, cout970 commented
Preview:
![image](https://github.com/user-attachments/assets/312b90ee-29d4-47e5-a956-ee9f888a14a9)
![image](https://github.com/user-attachments/assets/702e59d9-3aee-4648-b306-414907bf133a)

2024-12-03 18:19 UTC, cout970 commented
Requires https://github.com/openhotel/components/pull/7

2024-12-03 18:21 UTC, cout970 commented
![image](https://github.com/user-attachments/assets/97ed066d-6802-443c-8b27-3898dcaba3ad)
![image](https://github.com/user-attachments/assets/526891d9-d2a6-4cc8-970d-0dcc68d713cd)

2024-12-04 19:29 UTC, alqubo requested changes
Buen cambio

2024-12-04 19:29 UTC, alqubo commented on app/server/src/shared/consts/account.consts.ts
> +export const PASSWORD_REGEX = /^.{8,}$/;
Y este cambio? Libertad al usuario de poner la contraseña que quiera? Que es esto una democracia? @pagoru @cout970

2024-12-04 19:29 UTC, alqubo commented on README.md
> +- Install deps with `yarn install` at `app/client`
Ejecutando `deno task install` hace los dos installs.
Lo meti ayer en la sección Start project

2024-12-04 19:32 UTC, alqubo commented
@cout970 la nueva versión de components ya esta publicada [v0.1.8](https://github.com/openhotel/components/releases/tag/v0.1.8)

2024-12-04 21:44 UTC, cout970 commented on app/server/src/shared/consts/account.consts.ts
> +export const PASSWORD_REGEX = /^.{8,}$/;
La idea original era poner en el formulario de registro si tu contraseña no es válida, pero realmente creo que es mejor permitir cualquier cosa mientras tenga al menos 8 caracteres, es lo que recomienda OWASP y NIST por eso puse el link.

En un futuro se podria poner un indicador de complejidad de la contraseña

2024-12-05 16:35 UTC, cout970 commented on README.md
> +- Install deps with `yarn install` at `app/client`
He actualizado el README.md, ahora solo te indica que debes cambiar la versión a development, si no se cambia, los puertos no cuadran en local

2024-12-05 16:36 UTC, alqubo approved these changes

2024-12-05 16:37 UTC, merged